sap/sap/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from webapp.views import actualizarRegistro,registerView,registroexitoso,loginView,inicio,PaginaAdmin,salida, verUsuario, eliminarCuenta, agregarVehiculo, ServiciosList, paso ,pruebas, VerListService, eliminarRegistro

urlpatterns = [
    path('admin/', admin.site.urls),
    path('registro/',registerView, name="register"),
    path('registroexitoso/',registroexitoso),
    path('inicio/',inicio, name="inicio"),
    path('login/',loginView, name="login"),
    path('settings/',PaginaAdmin, name="confi"),
    path('logout',salida, name="salida"),
    path('verusuarios/', verUsuario, name="listauser"),
    path('eliminar/<int:userID>',eliminarCuenta, name="eliminar"),
    path('elminarRegistro/<int:servicioID>' , eliminarRegistro, name="eliminarVehiculo"),
    path('agregarVehiculo/',agregarVehiculo, name='agregar'),
    path('verservicios/', ServiciosList, name='listaservicios'),
    path('guardo/',paso, name='success'),
    path('pruebas/',pruebas),
    path('verlistavehiculo/', VerListService, name='verVehiculo'),
    path('actualizar/<int:vehiculoID>/', actualizarRegistro, name='actualizar')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sap/webapp/models.py
from django.db import models

# Create your models here.

sap/webapp/forms.py
from django import forms
from productos.models import Register

class formRegistro(forms.Form):
    email = forms.EmailField(label='Email:', required=True)
    name = forms.CharField(max_length=250, label='Nombre:', required=True)
    lastname = forms.CharField(max_length=250, label='Apellidos:', required=True)
    username = forms.CharField(max_length=250,label='Nombre de usuario:', required=True)
    password = forms.CharField(max_length=250, label='Contraseña:' ,required=True)

class formLogin(forms.Form):
    username = forms.CharField(max_length=250,label='Nombre de usuario:', required=True)
    password = forms.CharField(max_length=250, label='Contraseña:' ,required=True)

class ServicioForm(forms.Form):
    nombreProducto = forms.CharField(max_length=250, label= 'Nombre del producto', required=True)
    descripcionProducto = forms.CharField(max_length=250, label= 'Descripcion del producto', required=True)
    precioProducto = forms.CharField(max_length=250, label= 'Precio del producto', required=True)
    imagenProducto = forms.ImageField(label='Imagen del producto', required=True)

sap/webapp/views.py
from django.http import HttpResponse,Http404
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.models import User
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import authenticate, login, logout
from .forms import formRegistro, formLogin, ServicioForm
from productos.models import Register, Servicios

# Create your views here.
def registerView(request):
    if request.method == 'POST':
        form = formRegistro(request.POST)
        if form.is_valid():
            registroEmail = form.cleaned_data['email']
            registroName = form.cleaned_data['name']
            registroLastname = form.cleaned_data['lastname']
            registroUsername = form.cleaned_data['username']
            registroPassword = form.cleaned_data['password']
            nuevoRegistro = Register(email=registroEmail, name=registroName, lastname=registroLastname,
                                      username=registroUsername, password=registroPassword)
            nuevoRegistro.save()
            user = User.objects.create_user(
                username=registroUsername,
                password=registroPassword,
                email=registroEmail,
                first_name=registroName,
                last_name=registroLastname
            )
            user.save()
            return redirect('login')
    else:
        form = formRegistro()
    return render(request, 'Registro.html', {'form': form})

@staff_member_required
def verUsuario(request):
    query = request.GET.get('search')
    if query:
        users = Register.objects.filter(username=query)
    else:
        users = Register.objects.all()
    return render(request,'Listausers.html',{'users':users})

def eliminarCuenta(request, userID):
    try:
        userDB = get_object_or_404(Register, id=userID)
        userDB.delete()
    except Register.DoesNotExist:
        pass  # No se hace nada si el usuario no existe en la tabla Register

    userDJ = get_object_or_404(User, id=userID)
    userDJ.delete()

    return redirect('listauser')

def eliminarRegistro(request, servicioID):
    servicio = get_object_or_404(Servicios, id=servicioID)
    servicio.delete()

    return redirect('verVehiculo')

def registroexitoso(request):
    return render(request,'registroExitoso.html')

def inicio(request):
    servicios = Servicios.objects.all()
    return render(request,'index.html',{'servicios': servicios})

def loginView(request):
    if request.method == 'POST':
        form = formLogin(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username= username, password=password)
            if user is not None:
                login(request,user)
                return redirect('/inicio')
            else:
                form.add_error(None, 'Nombre de usuario o contraseña incorrectos')
    else:
        form = formLogin()
    return render(request,'Login.html', {'form':form})

@staff_member_required
def PaginaAdmin(request):
    return render(request,"paginaAdmin.html")

def salida(request):
    logout(request)
    return redirect('/login')

@staff_member_required
def agregarVehiculo(request):
    if request.method == 'POST':
        form = ServicioForm(request.POST, request.FILES)
        if form.is_valid():
            nombreProducto = form.cleaned_data['nombreProducto']
            descripcionProducto = form.cleaned_data['descripcionProducto']
            precioProducto = form.cleaned_data['precioProducto']
            imagenProducto = form.cleaned_data['imagenProducto']

            servis = Servicios(
                nombreProducto=nombreProducto,
                descripcionProducto=descripcionProducto,
                precioProducto=precioProducto,
                imagenProducto=imagenProducto
            )
            servis.save()
            return redirect('verVehiculo')
    else:
        form = ServicioForm()
    return render(request,'AggVehiculo.html',{'form':form})

@staff_member_required
def actualizarRegistro(request, vehiculoID):
    registro = get_object_or_404(Servicios, id = vehiculoID)
    if request.method == 'POST':
        form = ServicioForm(request.POST, request.FILES)
        if form.is_valid():
            registro.nombreProducto = form.cleaned_data['nombreProducto']
            registro.descripcionProducto = form.cleaned_data['descripcionProducto']
            registro.precioProducto = form.cleaned_data['precioProducto']
            if 'imagenProducto' in request.FILES:
                registro.imagenProducto = request.FILES['imagenProducto']
            registro.save()
            return redirect('verVehiculo')
    else:
        initial_data = {
            'nombreProducto': registro.nombreProducto,
            'descripcionProducto': registro.descripcionProducto,
            'precioProducto': registro.precioProducto,
        }
        form = ServicioForm(initial=initial_data)
    return render(request, 'ActualizarVehiculo.html', {'form': form})

@staff_member_required
def ServiciosList(request):
    servicios = Servicios.objects.all()
    return render(request,'verServicios.html',{'servicios': servicios})

@staff_member_required
def VerListService(request):
    query = request.GET.get('search')
    if query:
        servicios = Servicios.objects.filter(nombreProducto = query)
    else:
        servicios = Servicios.objects.all()
    return render(request,'tableService.html',{'servicios': servicios})


def paso(request):
    return HttpResponse('si guardo mi amor')

def pruebas(request):
    if request.method == 'POST':
        form = ServicioForm(request.POST, request.FILES)
        if form.is_valid():
            nombreProducto = form.cleaned_data['nombreProducto']
            descripcionProducto = form.cleaned_data['descripcionProducto']
            precioProducto = form.cleaned_data['precioProducto']
            imagenProducto = form.cleaned_data['imagenProducto']

            servis = Servicios(
                nombreProducto=nombreProducto,
                descripcionProducto=descripcionProducto,
                precioProducto=precioProducto,
                imagenProducto=imagenProducto
            )
            servis.save()
            return redirect('success')
    else:
        form = ServicioForm()
    return render(request,'pruebas.html',{'form':form})

sap/webapp/templates/ActualizarVehiculo.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Actualizar Vehículo</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'css/stylesAggvehiculo.css' %}">
</head>
<body>
    {% include 'components/menuAdmin.html' %}
    <div class="all">
        <div class="container">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <h1>Actualizar Vehículo</h1>
                <div class="inputs-box">
                    <input type="text" name="nombreProducto" id="id_nombreProducto" class="form-control" maxlength="50" placeholder="Referencia" required value="{{ form.nombreProducto.value }}">
                    <i class="bi bi-car-front-fill"></i>
                </div>
                <div class="inputs-box">
                    <input type="text" name="descripcionProducto" id="id_descripcionProducto" class="form-control" maxlength="250" placeholder="Descripción" required value="{{ form.descripcionProducto.value }}">
                    <i class="bi bi-card-text"></i>
                </div>
                <div class="inputs-box">
                    <input type="text" name="precioProducto" id="id_precioProducto" class="form-control" maxlength="50" placeholder="Precio" required value="{{ form.precioProducto.value }}">
                    <i class="bi bi-currency-dollar"></i>
                </div>
                <div class="inputs-box">
                    <input type="file" name="imagenProducto" id="id_imagenProducto" class="form-control">
                    <i class="bi bi-file-image-fill"></i>
                </div>
                <button type="submit" class="btn btn-primary">Actualizar</button>
            </form>
        </div>
    </div>
</body>
</html>

sap/webapp/templates/AggVehiculo.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'css/stylesAggvehiculo.css' %}">
</head>
<body>
    {% include 'components/menuAdmin.html' %}
    <div class="all">
        <div class="container">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <h1>Registro de vehiculos</h1>
                <div class="inputs-box">
                    <input type="text" name="nombreProducto" id="id_nombreProducto" class="form-control" maxlength="50" placeholder="Referencia" required>
                    <i class="bi bi-car-front-fill"></i>
                </div>
                <div class="inputs-box">
                    <input type="text" name="descripcionProducto" id="id_descripcionProducto" class="form-control" maxlength="250" placeholder="descripcion" required>
                    <i class="bi bi-card-text"></i>
                </div>
                <div class="inputs-box">
                    <input type="text" name="precioProducto" id="id_precioProducto" class="form-control" maxlength="50" placeholder="Precio" required>
                    <i class="bi bi-currency-dollar"></i>
                </div>
                <div class="inputs-box">
                    <input type="file" name="imagenProducto" id="id_imagenProducto" class="form-control" required>
                    <i class="bi bi-file-image-fill"></i>
                </div>
                <button type="submit" class="btn btn-primary">Guardar</button>
            </form>
        </div>
    </div>
</html>

sap/webapp/templates/Listausers.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/stylesListauser.css' %}">
</head>

<body>
    {% include 'components/menuAdmin.html' %}
    <div class="all">
        <div class="containerForm">
            <h2>Buscar:</h2>
            <form class="form" method="GET" action="">
                <input type="text" name="search" id="search" class="form-control">
                <label class="lbl-user" for="search">
                    <span class="txt-user">
                        Buscar por Nombre de usuario:
                    </span>
                </label>
                <button type="submit" class="btn btn-primary">Buscar</button>
            </form>
            <br>
            <br>
            <h2>Lista de Usuarios</h2>
            <div class="container">
                <table>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Email</th>
                            <th>Name</th>
                            <th>Lastname</th>
                            <th>Username</th>
                            <th>Eliminar</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in users %}
                        <tr>
                            <td>{{ user.id }}</td>
                            <td>{{ user.email }}</td>
                            <td>{{ user.name }}</td>
                            <td>{{ user.lastname }}</td>
                            <td>{{ user.username }}</td>
                            <td><a href="{% url 'eliminar' user.id %}" class="btn">Eliminar</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
</body>

</html>

sap/webapp/templates/Login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/stylesLogin.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>

<body>
    {% include 'components/menu.html' %}
    <div class="all">
        <div class="container">
            <form method="post">
                {% csrf_token %}
                <h1>Inicio de sesion</h1>
                <div class="inputs-box">
                    <input type="text" name="username" id="id_username" class="form-control" maxlength="250"
                        placeholder="Username">
                    <i class="bi bi-person-fill"></i>
                </div>
                <div class="inputs-box">
                    <input type="password" name="password" id="id_password" class="form-control" placeholder="Password"
                        maxlength="250" required>
                    <i class="bi bi-lock-fill"></i>
                </div>
                <div class="remember-forgot">
                    <label><input type="checkbox">Recuerdame</label>
                    <a href="#">Olvidemi contraseña</a>
                </div>
                <button type="submit" class="btn">Entrar</button>
                <div class="register-link">
                    <p>No tienes cuenta?<a href="{% url 'register' %}">Registrate</a></p>
                </div>
            </form>
            {% if form.non_field_errors %}
            <div class="alert-danger">
                {{ form.non_field_errors }}
            </div>
            {% endif %}
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
</body>

</html>

sap/webapp/templates/Registro.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'css/stylesRegister.css' %}">
</head>

<body>
    {% include 'components/menu.html' %}
    <div class="all">
        <div class="container">
            <form method="post">
                {% csrf_token %}
                <h1>Registro</h1>
                <div class="inputs-box">
                    <input type="email" name="email" id="id_email" class="form-control" placeholder="email" required>
                    <i class="bi bi-envelope-at-fill"></i>
                </div>
                <div class="inputs-box">
                    <input type="text" name="name" id="id_name" class="form-control" maxlength="250" placeholder="name" required>
                    <i class="bi bi-person-circle"></i>
                </div>
                <div class="inputs-box">
                    <input type="text" name="lastname" id="id_lastname" class="form-control" maxlength="250" placeholder="lastname" required>
                    <i class="bi bi-person-circle"></i>
                </div>
                <div class="inputs-box">
                    <input type="text" name="username" id="id_username" class="form-control" maxlength="250" placeholder="username" required>
                    <i class="bi bi-person-fill"></i>
                </div>
                <div class="inputs-box">
                    <input type="password" name="password" id="id_password" class="form-control" maxlength="250" placeholder="password" required>
                    <i class="bi bi-lock-fill"></i>
                </div>
                <div class="remember-forgot">
                    <label><input type="checkbox" required>Acepto terminos y condiciones</label>
                </div>
                <button type="submit" class="btn btn-primary">Registrarse</button>
            </form>
        </div>
    </div>
</body>

</html>

sap/webapp/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/stylesIndex.css' %}">
</head>

<body>
    {% include 'components/menuIndex.html' %}
    <div class="all">
        <h1 style="color: white; text-align: center;">Vehiculos Disponibles</h1>
        <hr style="height: 10px;
                    width: 50%;
                    background-color: white;
                    margin-left: 25%;">
        <div class="container">
            {% for servi in servicios %}
            <div class="box">
                <div class="imgBox">
                    <img src="{{ servi.imagenProducto.url }}" alt="">
                </div>
                <div class="details">
                    <div class="content">
                        <h2>{{ servi.nombreProducto }}</h2>
                        <p>{{ servi.descripcionProducto }}</p>
                        <p>{{ servi.precioProducto }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</body>

</html>

sap/webapp/templates/paginaAdmin.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body{
            background: linear-gradient(rgb(179, 27, 27),rgb(99, 26, 26));
        }

        .marquee {
            width: 100%;
            overflow: hidden;
            white-space: nowrap;
            box-sizing: border-box;
            width: 50%; /* O el ancho deseado */
            margin: 0 auto;
            text-align: center;
            padding-top: 20%;
        }

        .marquee span {
            display: inline-block;
            padding-left: 100%;
            animation: marquee 10s linear infinite;
            color:  rgb(255, 255, 255);
            font-family: "Poppins", sans-serif;
            font-size: 75px;
        }

        @keyframes marquee {
            from {
                transform: translateX(100%);
            }

            to {
                transform: translateX(-100%);
            }
        }
    </style>
</head>

<body>
    {% include 'components/menuAdmin.html' %}

    <div class="marquee">
        <span>Hola administradores.</span>
    </div>

</body>

</html>

sap/webapp/templates/pruebas.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'css/stylesAggvehiculo.css' %}">
</head>

<body>
    {% include 'components/menuAdmin.html' %}
    <div class="all">
        <div class="container">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <h1>Registro de vehiculos</h1>
                <div class="inputs-box">
                    <input type="text" name="nombreProducto" id="id_nombreProducto" class="form-control" maxlength="50" placeholder="Referencia" required>
                    <i class="bi bi-car-front-fill"></i>
                </div>
                <div class="inputs-box">
                    <input type="text" name="descripcionProducto" id="id_descripcionProducto" class="form-control" maxlength="250" placeholder="descripcion" required>
                    <i class="bi bi-card-text"></i>
                </div>
                <div class="inputs-box">
                    <input type="text" name="precioProducto" id="id_precioProducto" class="form-control" maxlength="50" placeholder="Precio" required>
                    <i class="bi bi-currency-dollar"></i>
                </div>
                <div class="inputs-box">
                    <input type="file" name="imagenProducto" id="id_imagenProducto" class="form-control" required>
                    <i class="bi bi-file-image-fill"></i>
                </div>
                <button type="submit" class="btn btn-primary">Registrarse</button>
            </form>
        </div>
    </div>
    
    <!--
    <div class="all">
        <h1>Agregar Servicio</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="text" name="nombreProducto" id="id_nombreProducto" class="form-control" maxlength="50"
                required>
            <label class="lbl-user" for="search">
                <span class="txt-user">
                    Buscar por Nombre de usuario:
                </span>
            </label>

            <input type="text" name="descripcionProducto" id="id_descripcionProducto" class="form-control"
                maxlength="250" required>

            <input type="text" name="precioProducto" id="id_precioProducto" class="form-control" maxlength="50"
                required>

            <input type="file" name="imagenProducto" id="id_imagenProducto" class="form-control" required>
            <button type="submit" class="btn">Agregar</button>
        </form>
    </div>-->
</body>

</html>

sap/webapp/templates/registroExitoso.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>si</p>
    <a href="{% url 'inicio' %}">index</a>
</body>
</html>

sap/webapp/templates/tableService.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/styleListvehiculo.css' %}">
</head>

<body>
    {% include 'components/menuAdmin.html' %}
    <div class="all">
        <div class="containerForm">
            <h2>Buscar:</h2>
            <form class="form" method="GET" action="">
                <input type="text" name="search" id="search" class="form-control">
                <label class="lbl-service" for="search">
                    <span class="txt-service">
                        Buscar
                    </span>
                </label>
            </form>
            <br>
            <br>
            <h2>Lista de Usuarios</h2>
            <div class="container">
                <table>
                    <thead>
                        <tr>
                            <th>Nombre Producto</th>
                            <th>Descripcion Producto</th>
                            <th>Precio Producto</th>
                            <th>Imagen Producto</th>                            
                            <th>Eliminar</th>
                            <th>Actualizar</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for service in servicios %}
                        <tr>
                            <td>{{ service.nombreProducto }}</td>
                            <td>{{ service.descripcionProducto }}</td>
                            <td>{{ service.precioProducto }}</td>
                            <td><img src="{{ service.imagenProducto.url }}" class="product-image"></td>
                            <td><a href="{% url 'eliminarVehiculo' service.id %}" class="btn">Eliminar</a></td>
                            <td><a href="{% url 'actualizar' vehiculoID=service.id %}">Actualizar</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>

</html>

sap/webapp/templates/verServicios.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for servi in servicios %}
    <h1>nombre: {{ servi.nombreProducto }}</h1>
    <p>Descripcion: {{ servi.descripcionProducto }}</p>
    <h5>Precio: {{ servi.precioProducto }}</h5>
    <img src="{{ servi.imagenProducto.url }}">
    {% endfor %}
</body>
</html>